name: portable-release-actions-workflow
on:
  push:

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - shell: cmd
        run: |
          curl https://github.com/dirkarnez/regex-file-replace/releases/download/v1.0.0/regex-file-replace-v1.0.0-windows-latest.zip -L -O &&^
          7z x regex-file-replace-v1.0.0-windows-latest.zip &&^
          .\regex-file-replace.exe --regex="^cmd = .*" --replacement="cmd = \"\"Fusion360.exe\"\"" --filepath=FusionLauncher.exe.ini &&^
          type FusionLauncher.exe.ini
