name: portable-release-actions-workflow
on:
  push:

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find and Replace
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: '/^cmd\s+=.*$/gm'
          replace: 'cmd = ""Fusion360.exe""'
          include: 'FusionLauncher.exe.ini'

      - shell: bash
        run: cat FusionLauncher.exe.ini
