name: portable-release-actions-workflow
on:
  push:

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Modify version number
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: '^cmd\\s+=\\s+.*'
          replacement: 'cmd = ""Fusion360.exe""'
          flags: "g"                  # Optional, defaults to "g"
          include: 'FusionLauncher.exe.ini'    # Optional, defaults to ".*"
          
      - shell: cmd
        run: type FusionLauncher.exe.ini
